### ISSUE TITLE
Please add support for VEGA FE and Radeon VII

### ISSUE THREAD

**Issue by Josevora** [EPICBOOST/ePIC-Boost-Miner#1]
Hello,
If i Try to run this with them, I get an " __3ccd__" error...
Are you going to add support for those cards?

Thank you.

PS - If you need access to both, i'll grant that for you...

**Comment by EPICBOOST** [comment]
Hi Josevora,

Thanks for your interest. At this time, we are only supporting the Sapphire RX570 16GB cards.

We will keep you posted if things change.

Best Regards, 
ePIC Support
