### ISSUE TITLE
[FEATURE REQUEST] Support cycle length other than 42

### ISSUE THREAD

**Issue by sebseb7** [EPICBOOST/ePIC-Boost-Miner#4]
Hi,

more coins will use cuckaroo/cuckatoo. To disable nicehash they may chose a different cycle length. Also please allow the pool to reduce the nonce to at least 32 bit ( 8 bytes -> 4 bytes ).

for regression: 

this is cuckaroo29 with a 32 cycle and 4 bytes nonce, (see gminer).

https://github.com/swap-dev/micropool-gui

**Comment by EPICBOOST** [comment]
Hi sebseb7,

Thanks for the suggestion. Our current plan is to focus on Grin, but we will review this and perhaps release an update in the future.
