### ISSUE TITLE
Reinstalling AMD GPU Pro

### ISSUE THREAD

**Issue by RedRockMining** [EPICBOOST/ePIC-Boost-Miner#5]
Hi, all was going well then I had a power outage. After rebooting I now get an immediate "segmentation fault" error on EB startup. I've tried every general repair/reinstall procedure I could find including uninstalling and reinstalling both EB and AMD GPU Pro but the error persists. I noticed when reinstalling AMD GPU Pro, I get WARNING: amdgpu dkms failed for running kernel. I found that others were experiencing the same. A forum suggestion was to run "apt install amdgpu-dkms libdrm-amdgpu-amdgpu1 libdrm-amdgpu1 libdrm2-amdgpu" to get missing packages, but that did not help.

Any thoughts besides yet another clean Linux install/start over?

JTW

**Comment by EPICBOOST** [comment]
This is a result of an AMD driver issue. We will be adding a fix to rectify in our next release.
